// Ícones do app: Phosphor (phosphoricons.com), exportados com os nomes que o código já usa.
// Pra trocar um ícone, troque só aqui.
import type { Icon } from "@phosphor-icons/react"
export type { Icon }
export type LucideIcon = Icon

export {
  Warning as AlertTriangle,
  Warning as TriangleAlertIcon,
  Archive,
  ArrowDown, ArrowDownLeft, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight,
  ArrowsLeftRight as ArrowLeftRight,
  Prohibit as Ban,
  Money as Banknote,
  ChartBar as BarChart3,
  ChartBar as ChartColumnStacked,
  ChartLine as ChartSpline,
  BeerBottle as Beer,
  Bell, BookOpen, Briefcase, Cake, Calculator,
  CalendarBlank as Calendar,
  CalendarBlank as CalendarRange,
  CalendarCheck,
  CalendarDots as CalendarClock,
  CalendarDots as CalendarDays,
  Car,
  Check,
  Check as CheckIcon,
  Checks as CheckCheck,
  CheckCircle as CheckCircle2,
  CheckCircle as CircleCheck,
  CheckCircle as CircleCheckIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUpIcon,
  Circle,
  Circle as CircleIcon,
  WarningCircle as CircleAlert,
  CurrencyCircleDollar as CircleDollarSign,
  Gauge as CircleGauge,
  Gauge,
  ClipboardText as ClipboardCheck,
  Clock, Coffee, Copy, CreditCard,
  PintGlass as CupSoda,
  CurrencyDollar as DollarSign,
  DownloadSimple as Download,
  Barbell as Dumbbell,
  Eye,
  EyeSlash as EyeOff,
  CheckSquare as FileCheck2,
  FileArrowDown as FileDown,
  FileText, Flag,
  Fire as Flame,
  Flask as FlaskRound,
  GasPump as Fuel,
  GameController as Gamepad2,
  Gift,
  Target as Goal,
  GraduationCap, HandCoins,
  Heartbeat as HeartPulse,
  ClockCounterClockwise as History,
  House as Home,
  IceCream,
  Tray as Inbox,
  Info,
  Info as InfoIcon,
  Bank as Landmark,
  Laptop,
  Stack as Layers,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  Lightbulb, Link, List, ListChecks,
  ListNumbers as ListOrdered,
  CircleNotch as Loader2,
  CircleNotch as Loader2Icon,
  Lock, Martini,
  Microphone as Mic,
  Minus, Moon,
  DotsThree as MoreHorizontal,
  CursorClick as MousePointerClick,
  MusicNotes as Music,
  XCircle as OctagonXIcon,
  LetterCircleP as ParkingCircle,
  Confetti as PartyPopper,
  PencilSimple as Pencil,
  ChartPie as PieChart,
  PiggyBank, Pill, Pizza,
  Airplane as Plane,
  Plus, Popcorn, Receipt,
  Receipt as ReceiptText,
  Repeat,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  Scales as Scale,
  Student as School,
  Scissors,
  MagnifyingGlass as Search,
  PaperPlaneRight as Send,
  Sliders as Settings2,
  Shapes,
  TShirt as Shirt,
  Handbag as ShoppingBag,
  ShoppingCart, Sigma, SlidersHorizontal,
  DeviceMobile as Smartphone,
  Sparkle as Sparkles,
  SprayBottle as SprayCan,
  Stethoscope, Sun, Tag, ThumbsDown, Ticket,
  Trash as Trash2,
  TreePalm,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Trophy,
  Television as Tv,
  ArrowUUpLeft as Undo2,
  LockOpen as Unlock,
  UploadSimple as Upload,
  ForkKnife as Utensils,
  ForkKnife as UtensilsCrossed,
  Wallet, Wine, Wrench, X,
  X as XIcon,
  XCircle,
  Lightning as Zap,
} from "@phosphor-icons/react"
